### ISSUE TITLE
Error 'ps_mwa' function

### ISSUE THREAD

**Issue by BermudezA** [ivostuldreher/robustness-of-physiological-synchrony#1]
Hi, 

We are exploring physiological synchrony to analyse our EEG and EDA data. 
We are trying to use your scripts in MATLAB 2023 we get an error message: 'ps_mwa' function not found
Please, can you check?

Thanks in advance
Cheers,

Alejandra

**Comment by ivostuldreher** [comment]
Hi Alejandra,

Thanks for your request. I am currently on holiday and don't have access to
a computer. It seems I have missed the ps_mwa function in the push to git.
I will upload the function once I am back.

Best regards, Ivo

Op di 25 apr. 2023 14:59 schreef Alejandra Bermudez <
***@***.***>:

**Comment by ivostuldreher** [comment]
Function has been uploaded, issue should be resolved.

**Comment by BermudezA** [comment]
Thank you very much Ivo
